### ISSUE TITLE
Support for RancherOS v0.8.0 Specifications

### ISSUE THREAD

**Issue by matthewhartstonge** [joshwget/validator#1]
Hey Josh,

First off, thanks for the validator! (Saves me bringing up EC2 instances whimsically to test feature parity)
Secondly, is this up to date with RancherOS v0.8.0 spec?
Lastly, what is the feature parity between cloud-init and rancheros cloud-init/config? The docs for RancherOS seem a little off/not up to date around this..

Thanks for your hard work on Rancher! 😄

**Comment by joshwget** [comment]
As it seems you've already noticed in #2 this is slightly out of date :sweat: 

There's a bit of refactoring I'd like to do to keep this up to date in the future. I'll create an issue for that.

**Comment by matthewhartstonge** [comment]
Closing as #3 should fix this 👍
